apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-service-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query-service
  template:
    metadata:
      labels:
        app: query-service
    spec:
      containers:
        - name: query-service
          image: willchrist/query-service:d9b3c6f
          ports:
            - containerPort: 8002
          env:
            - name: PORT_PRODUCT
              value: "8001"
            - name: QUERY_SERVICE_PORT
              value: "8002"
            - name: PRODUCT_SERVICE_PORT
              value: "8001"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_REGION
              value: "us-east-1"
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"
          startupProbe:
            httpGet:
              path: /query?q=startup
              port: 8002
            failureThreshold: 12
            periodSeconds: 10
            timeoutSeconds: 10
