apiVersion: v1
kind: Service
metadata:
  name: query-service
  namespace: default
spec:
  selector:
    app: query-service
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
  type: ClusterIP
